name: Build and Deploy

on:
  push:
    branches-ignore:
      - "master"
      - "stage"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup node environment"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: "Install dependencies"
        run: |
          npm install
          npm install -g aws-cdk

      - name: "Setup Go environment"
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: "Package build files"
        run: |
          chmod +x ./build_package.sh
          ./build_package.sh

      - name: "Run CDK infrastructure test"
        run: |
          cd infra
          npm run build && npm test
